employee:
    type:         rest
    resource:     Budget\RESTBudgetBundle\Controller\EmployeeController
    name_prefix:  api_v1_

occupation:
    type:         rest
    resource:     Budget\RESTBudgetBundle\Controller\OccupationController
    name_prefix:  api_v1_

project:
    type:         rest
    resource:     Budget\RESTBudgetBundle\Controller\ProjectController
    name_prefix:  api_v1_

involvement:
    type:         rest
    resource:     Budget\RESTBudgetBundle\Controller\ProjectInvolvementController
    name_prefix:  api_v1_