services:
  budget.serialization.employee_listener:
    class: Budget\RESTBudgetBundle\Listener\EmployeeSerializationListener
    tags:
      - { name: jms_serializer.event_listener, event: serializer.pre_serialize, method: onPreSerialize, class: Budget\BudgetBundle\Entity\Employee }
      - { name: jms_serializer.event_listener, event: serializer.post_serialize, method: onPostSerialize, class: Budget\BudgetBundle\Entity\Employee }
    arguments: [@security.context, @em]