crud_employee:
    pattern:  /
    defaults: { _controller: "BudgetBundle:Employee:index" }

crud_employee_show:
    pattern:  /{id}/show
    defaults: { _controller: "BudgetBundle:Employee:show" }

crud_employee_new:
    pattern:  /new
    defaults: { _controller: "BudgetBundle:Employee:new" }

crud_employee_create:
    pattern:  /create
    defaults: { _controller: "BudgetBundle:Employee:create" }
    requirements: { _method: post }

crud_employee_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BudgetBundle:Employee:edit" }

crud_employee_update:
    pattern:  /{id}/update
    defaults: { _controller: "BudgetBundle:Employee:update" }
    requirements: { _method: post|put }

crud_employee_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BudgetBundle:Employee:delete" }
    requirements: { _method: post|delete }
