<?php

namespace Budget\BudgetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectInvolvementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectInvolvementRepository extends EntityRepository
{
}
