<?php

namespace Budget\BudgetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpendingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpendingsRepository extends EntityRepository
{
}
