<?php

namespace Budget\BudgetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpendingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpendingsRepository extends EntityRepository
{

    public function hasDaySpendings(\DateTime $date)
    {
        $query = $this->createQueryBuilder('spendings')
            ->select('COUNT(spendings)')
            ->where('spendings.date = :date')

            ->setParameter('date', $date->format('Y-m-d'))

            ->getQuery();

        return $query->getSingleScalarResult() != 0;

    }

    public function clearDaySpendings(\DateTime $date)
    {
        $result = $this->getEntityManager()
            ->createQuery('DELETE FROM Budget\\BudgetBundle\\Entity\\Spendings s WHERE s.date=:date')
            ->setParameter('date', $date->format('Y-m-d'))
            ->execute();

        return $result;
    }

    public function projectSpendings(Project $project, \DateTime $startDate = null, \DateTime $endDate = null)
    {
        $result = $this->createNativeNamedQuery('spendings')
            ->setSQL('SELECT speindgs')
            ->execute();

        return $result;
    }

}
