services:
  budget.serialization.employee_listener:
    class: Checkman\RESTCheckmanBundle\Listener\EmployeeSerializationListener
    tags:
      - { name: jms_serializer.event_listener, event: serializer.pre_serialize, method: onPreSerialize, class: Checkman\CheckmanBundle\Entity\Employee }
      - { name: jms_serializer.event_listener, event: serializer.post_serialize, method: onPostSerialize, class: Checkman\CheckmanBundle\Entity\Employee }
    arguments: [@security.context, @em]

  budget.serialization.spendings_listener:
    class: Checkman\RESTCheckmanBundle\Listener\EmployeeSerializationListener
    tags:
      - { name: jms_serializer.event_listener, event: serializer.pre_serialize, method: onPreSerialize, class: Checkman\CheckmanBundle\Entity\Employee }
      - { name: jms_serializer.event_listener, event: serializer.post_serialize, method: onPostSerialize, class: Checkman\CheckmanBundle\Entity\Employee }
    arguments: [@security.context, @em]