rest_budget:
    resource: "@RESTBudgetBundle/Controller/"
    type:     annotation
    prefix:   /

users:
    type:     rest
    prefix:   /api/v1
    resource: "@RESTBudgetBundle/Resources/config/rest_routes_v1.yml"

budget:
    resource: "@BudgetBundle/Controller/"
    type:     annotation
    prefix:   /

application:
    resource: "@ApplicationBundle/Controller/"
    type: annotation
    prefix:   /

