<?php

namespace Checkman\CheckmanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends EntityRepository
{

    public function getActiveEmployees()
    {
        return $this->findByStatus(Employee::STATUS_ACTIVE);
    }

}
