<?php

namespace Checkman\CheckmanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpendingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    public function getSharedProjectsByRegionId($regionId)
    {
        return $this->findBy([
            'region_id' => $regionId
        ]);
    }

    public function getLostMoneyProject()
    {
        return $this->findOneBy([
            'title' => '[==Простой сотрудников==]'
        ]);
    }
}