parameters:
    budget.reports.class: Budget\BudgetBundle\Service\Reports
    budget.history.class: Budget\BudgetBundle\Service\History

services:
    budget.reports:
        class: %budget.reports.class%
        arguments: [@service_container]

    budget.history:
        class: %budget.history.class%
        arguments: [@service_container]
