parameters:
    checkman.reports.class: Checkman\CheckmanBundle\Service\Reports
    checkman.history.class: Checkman\CheckmanBundle\Service\History

services:
    checkman.reports:
            class: Checkman\CheckmanBundle\Service\Factory
            arguments: [@service_container]

    checkman.reports.general:
        class: %checkman.reports.class%
        factory_service: checkman.reports
        factory_method: getReportsForCurrentUser

    checkman.reports.history:
        class: %checkman.history.class%
        arguments: [@service_container]
