parameters:
    checkman.reports.class: Checkman\CheckmanBundle\Service\Reports
    checkman.history.class: Checkman\CheckmanBundle\Service\History

services:
    checkman.services.factory:
        class: Checkman\CheckmanBundle\Service\Factory
        arguments: [@service_container]

    checkman.reports:
        class: %checkman.reports.class%
        factory_service: checkman.services.factory
        factory_method: getReportsForCurrentUser

    checkman.history:
        class: %checkman.history.class%
        arguments: [@service_container]
