parameters:
    budget.reports.class: Checkman\CheckmanBundle\Service\Reports
    budget.history.class: Checkman\CheckmanBundle\Service\History

services:
    budget.services.factory:
        class: Checkman\CheckmanBundle\Service\Factory
        arguments: [@service_container]

    budget.reports:
        class: %budget.reports.class%
        factory_service: budget.services.factory
        factory_method: getReportsForCurrentUser

    budget.history:
        class: %budget.history.class%
        arguments: [@service_container]
